# Generated by Django 5.1.5 on 2025-01-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_introduction', models.CharField(max_length=500)),
                ('course_description', models.TextField()),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('preview_video_link', models.URLField()),
                ('tags', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('upcoming', models.BooleanField(default=False)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('paid_course', models.BooleanField(default=False)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
