# Generated by Django 5.1.5 on 2025-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
