# Generated by Django 5.1.5 on 2025-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
